KISSG/Controllers/GeneratorController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using KISSG.Templates.OnePageSite;
using KISSG.Services;

namespace KISSG.Controllers
{   
    public class GeneratorController : Controller
    {
        private HtmlGeneratorService service = new HtmlGeneratorService();
        
        public IActionResult Index()
        {
            return View();
        }
    
        [HttpGet]
        public IActionResult WelcomeTemplate()
        {
            return View("CreateWelcome");
        }

        
        [HttpPost]
        public async Task<IActionResult> WelcomeTemplate([Bind("SiteName,FirstSectionColor,LogoUrl,Motto,MottoColor," +
            "MainSectionBgColor,MainSectionTxtColor,MainSection,PictureUrl,Projects,ContactSectionBgColor," +
            "ContactSectionTxtColor,Email,Phone,Address")] Welcome welcome)
        {
            if (ModelState.IsValid)
            {
               await service.GenerateHtmlResponse(welcome, Response);
            }
            
            return View("Index");
        }
        
    }
}

KISSG/Views/Generator/CreateWelcome.cshtml
@model KISSG.Templates.OnePageSite.Welcome

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <style>
        input , label {
            display:inline-block;
        }
    </style>

</head>
<body style="padding-left:20vh; padding-right:20vh; background-image:url(https://i.imgur.com/QgQRIAl.gif); background-size:100% 100%; background-repeat:no-repeat">

<h4 align="center" style="color:white">Welcome Template</h4>
<hr />
<div class="row" >
    <div class="col-md-4" style="margin:20px">
        <form asp-action="WelcomeTemplate" style="overflow-y:scroll; height:85vh">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SiteName" class="control-label"></label>
                <input asp-for="SiteName" class="form-control" />
                <span asp-validation-for="SiteName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstSectionColor" class="control-label"></label>
                <input type="color" asp-for="FirstSectionColor" class="form-control" />
                <span asp-validation-for="FirstSectionColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LogoUrl" class="control-label"></label>
                <input asp-for="LogoUrl" class="form-control" />
                <span asp-validation-for="LogoUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Motto" class="control-label"></label>
                <input asp-for="Motto" class="form-control" />
                <span asp-validation-for="Motto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MottoColor" class="control-label"></label>
                <input type="color" asp-for="MottoColor" class="form-control" />
                <span asp-validation-for="MottoColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MainSectionBgColor" class="control-label"></label>
                <input type="color" asp-for="MainSectionBgColor" class="form-control" />
                <span asp-validation-for="MainSectionBgColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MainSectionTxtColor" class="control-label"></label>
                <input type="color" asp-for="MainSectionTxtColor" class="form-control" />
                <span asp-validation-for="MainSectionTxtColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MainSection" class="control-label"></label>
                <input asp-for="MainSection" class="form-control" />
                <span asp-validation-for="MainSection" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PictureUrl" class="control-label"></label>
                <input asp-for="PictureUrl" class="form-control" />
                <span asp-validation-for="PictureUrl" class="text-danger"></span>
            </div>
            <div id="work">
                <div class="form-group">
                    <label asp-for="Projects[0]" class="control-label"></label>
                    <input asp-for="Projects[0]" class="form-control" />
                    <span asp-validation-for="Projects[0]" class="text-danger"></span>
                </div>
            </div>
            <i class="fas fa-plus-circle" style="color:purple; float:right ; display:block ; clear:both" onclick="addProject()">Add project</i>
            <div class="form-group">
                <label asp-for="ContactSectionBgColor" class="control-label"></label>
                <input type="color" asp-for="ContactSectionBgColor" class="form-control" />
                <span asp-validation-for="ContactSectionBgColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactSectionTxtColor" class="control-label"></label>
                <input type="color" asp-for="ContactSectionTxtColor" class="form-control" />
                <span asp-validation-for="ContactSectionTxtColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Generate" class="btn btn-success btn-lg btn-block" />
            </div>
        </form>
    </div>
    <div class="col-md-4">
        <img src="https://i.imgur.com/9Vfyf2S.jpg"  alt="Loading failed" style="height:90vh"/>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    var index = 1;

    function addProject() {
        var elem = document.getElementById("work");
        var str = '<div class="form-group">\n';
        str += '<label class="control-label" for="Projects_'+index+'_" >Projects['+index+']</label>\n'
        str += '<input class="form-control" type="text" id="Projects_'+index+'_"  name="Projects['+index+']" value >\n'
        str += '<span class="text-danger field-validation-valid" data-valmsg-for="Projects[' + index + ']"  ></span>\n'
        str += '</div>';
        index++;
        elem.insertAdjacentHTML('beforeend', str);
    }
</script>

    


</body>
</html>

KISSG/Views/Generator/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>KISSG - At your service</title>
</head>
<body style="overflow:hidden">
    <div style="height:100vh; text-align: center; color:white; background-image:url(http://3.bp.blogspot.com/-VyrWLqXDRdM/WKIXcIQVSYI/AAAAAAAADjk/j-2-j_fxsEU4DjYVJzGuYb5iasFkpP__gCHM/s1600/cool-abstract-background-hd-desktop-wallpaper-high-definition.jpg); background-repeat:no-repeat; background-size: cover">
   
    @Html.ActionLink("Create Welcome site", "WelcomeTemplate" , "Generator" , 
    null, new { @class="btn btn-outline-dark btn-lg", @style="position: absolute; top:50%"})
    </div>
</body>
</html>

KISSG/Views/welcomes/Edit.cshtml
@model KISSG.Templates.OnePageSite.welcome

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>welcome</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstSectionColor" class="control-label"></label>
                <input asp-for="FirstSectionColor" class="form-control" />
                <span asp-validation-for="FirstSectionColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LogoUrl" class="control-label"></label>
                <input asp-for="LogoUrl" class="form-control" />
                <span asp-validation-for="LogoUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Motto" class="control-label"></label>
                <input asp-for="Motto" class="form-control" />
                <span asp-validation-for="Motto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MottoColor" class="control-label"></label>
                <input asp-for="MottoColor" class="form-control" />
                <span asp-validation-for="MottoColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MainSectionBgColor" class="control-label"></label>
                <input asp-for="MainSectionBgColor" class="form-control" />
                <span asp-validation-for="MainSectionBgColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MainSectionTxtColor" class="control-label"></label>
                <input asp-for="MainSectionTxtColor" class="form-control" />
                <span asp-validation-for="MainSectionTxtColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MainSection" class="control-label"></label>
                <input asp-for="MainSection" class="form-control" />
                <span asp-validation-for="MainSection" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PictureUrl" class="control-label"></label>
                <input asp-for="PictureUrl" class="form-control" />
                <span asp-validation-for="PictureUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Projects" class="control-label"></label>
                <input asp-for="Projects" class="form-control" />
                <span asp-validation-for="Projects" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactSectionBgColor" class="control-label"></label>
                <input asp-for="ContactSectionBgColor" class="form-control" />
                <span asp-validation-for="ContactSectionBgColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactSectionTxtColor" class="control-label"></label>
                <input asp-for="ContactSectionTxtColor" class="form-control" />
                <span asp-validation-for="ContactSectionTxtColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>